const db = require("./connection");
const { User, Product, Category } = require("../models");

db.once("open", async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { name: "Coding Mindset" },
    { name: "Computer Science" },
    { name: "HTML & CSS" },
    { name: "Advanced CSS" },
    { name: "JavaScript" },
    { name: "APIs" },
    { name: "Node & Express" },
    { name: "SQL & NoSQL" },
    { name: "React" },
    { name: "Full Stack" },
    { name: "Git" },
    { name: "Python" },
  ]);

  console.log("categories seeded");

  await Product.deleteMany();

  const products = await Product.insertMany([
    {
      name: "100 Days of Code",
      author: "Holly Boothroyd",
      description: "Take the 100 Days of Code challenge! For 100 days, for just an hour a day invest in yourself by taking the time to improve your tech skills and ultimately make progress toward your goals.",
      image: "MENTALITY-coding-journal.jpg",
      category: categories[0]._id,
      price: 15.99,
      quantity: 500,
    },
    {
      name: "The Pragmatic Programmer",
      author: "David Thomas and Andrew Hunt",
      description: "The Pragmatic Programmer: From Journeyman to Master is a book about computer programming and software engineering, written by Andrew Hunt and David Thomas and published in October 1999. It is used as a textbook in related university courses.",
      image: "MENTALITY-the-pragmatic-programmer.jpg",
      category: categories[0]._id,
      price: 39.99,
      quantity: 500,
    },
    {
      name: "The Self-Taught Programmer",
      author: "Cory Althoff",
      category: categories[0]._id,
      description: "Cory Althoff is a self-taught programmer. After a year of self-study, he learned to program well enough to land a job as a software engineer II at eBay. But once he got there, he realised he was severely under-prepared. He was overwhelmed by the amount of things he needed to know but hadn't learned. His journey learning to program, and his experience in first software engineering job were the inspiration for this book.This book is not just about learning to program, although you will learn to code. If you want to program professionally, it is not enough to learn to code; that is why, in addition to helping you learn to program, Althoff also cover the rest of the things you need to know to program professionally that classes and books dont teach you. The Self-taught Programmer is a roadmap, a guide to take you from writing your first Python program to passing your first technical interview.",
      image: "MENTALITY-the-self-taught-programmer.jpg",
      price: 19.68,
      quantity: 20,
    },
    {
      name: "The Unicorn Project",
      author: "Gene Kim",
      category: categories[0]._id,
      description:
        "In The Unicorn Project, we follow Maxine, a senior lead developer and architect, as she is exiled to the Phoenix Project, to the horror of her friends and colleagues, as punishment for contributing to a payroll outage.",
      image: "MENTALITY-the-unicorn-project.jpg",
      price: 26.99,
      quantity: 50,
    },
    {
      name: "Think Like a Programmer",
      author: "V. Anton Spraul",
      category: categories[0]._id,
      description: "Programming isnt just about syntax and assembling code—its about problem solving, and all good programmers must think creatively to solve problems. Like the best-selling Think Like a Programmer before it (with over 75,000 copies sold worldwide), this Python-based edition will help you transition from reading programs to writing them, in, Python. (No prior programming experience required. Rather than simply point out solutions to problems, author V. Anton Spraul will get you thinking by exposing you to techniques that will teach you how to solve programming problems on your own. Each chapter covers a single programming concept like data types, control flow, code reuse, recursion, and classes, then a series of Python-based exercises have you put your skills to the test.",
      image: "MENTALITY-think-like-a-programmer.jpg",
      price: 19.89,
      quantity: 100,
    },
    {
      name: "Cambridge IGCSE Computer Science",
      author: "Richard Morgan",
      category: categories[1]._id,
      description: "Cambridge IGCSE Computer Science helps learners develop an interest in computational thinking and an understanding of the principles of problem-solving using computers. They apply this understanding to create computer-based solutions to problems using algorithms and a high-level programming language. Learners also develop a range of technical skills, and the ability to effectively test and evaluate computing solutions.",
      image: "cambridge.jpg",
      price: 33.70,
      quantity: 30,
    },
    {
      name: "Everything You Need to Ace Computer Science and Coding In One Big Fat Book",
      author: "Workman Publishing",
      category: categories[1]._id,
      description: "The Big Fat Notebooks revolutionized the study guide for middle schoolers, and students, parents, and teachers responded—the series has nearly 4 million copies in print with sales escalating every year. Now introducing Everything You Need to Ace Computer Science and Coding, an essential new title with the potential to run hand-in-hand with—or even outrun—Math (over 1.3 million copies in print) and Science (925,000 copies in print) as the next critical STEM companion. Instruction is presented in the simple but powerful format of the previous Big Fat Notebooks. The key concepts of coding and computer science easily digested and summarized, with critical ideas clearly explained, doodles that illuminate tricky concepts, and quizzes to recap it all. Kids will explore the concepts of computer science, learn how websites are designed and created, and understand the fundamentals of coding with Scratch, Python, HTML, and CSS. ",
      image: "COMPUTER-SCIENCE-everything-you-need-to-ace.jpg",
      price: 10.99,
      quantity: 30,
    },
    {
      name: "A Programmer's Guide to Computer Science",
      author: "William M. Springer II, PhD",
      category: categories[1]._id,
      description: "You know how to code..but is it enough?Do you feel left out when other programmers talk about asymptotic bounds?Have you failed a job interview because you don't know computer science?The author, a senior developer at a major software company with a PhD in computer science, takes you through what you would have learned while earning a four-year computer science degree. Volume one covers the most frequently referenced topics, including:-Algorithms and data structures-Graphs-Problem-solving techniques-Complexity theoryWhen you finish this book, you'll have the tools you need to hold your own with people who have - or expect you to have - a computer science degree.",
      image: "COMPUTER-SCIENCE-programmers-guide-to-computer-science.jpg",
      price: 26.99,
      quantity: 100,
    },
    {
      name: "Programming Machine Learning",
      author: "Paolo Perrotta",
      category: categories[1]._id,
      description: "A zero-to-hero machine learning tutorial for software developers, from simple programs to deep learning.",
      image: "COMPUTER-SCIENCE-programming-machine-learning.jpg",
      price: 38.49,
      quantity: 1000,
    },
    {
      name: "Programming the Universe",
      author: "Seth Lloyd",
      category: categories[1]._id,
      description: "Is the universe actually a giant quantum computer? According to Seth Lloyd, the answer is yes. All interactions between particles in the universe, Lloyd explains, convey not only energy but also information–in other words, particles not only collide, they compute. What is the entire universe computing, ultimately? “Its own dynamical evolution,” he says. “As the computation proceeds, reality unfolds.” Programming the Universe, a wonderfully accessible book, presents an original and compelling vision of reality, revealing our world in an entirely new light.",
      image: "COMPUTER-SCIENCE-programming-the-universe.jpg",
      price: 15.29,
      quantity: 1000,
    },
    {
      name: "HTML5 and CSS3 All-In-One For Dummies",
      author: "Andy Harris",
      category: categories[2]._id,
      description: "HTML5 and CSS3 are essential tools for creating dynamic websites and boast updates and enhanced features that can make your websites even more effective and unique. This friendly, all-in-one guide covers everything you need to know about each of these technologies and their latest versions so that you can use them together. Building on the bestselling formats of the first two editions, this new edition teaches you the fundamentals of HTML5 and CSS3, and then presents ways for using them with JavaScript, MySQL, and Ajax to create websites that work.",
      image: "HTML-CSS-html-css-for-dummies.jpeg",
      price: 27.99,
      quantity: 100,
    },
    {
      name: "HTML & CSS",
      author: "Jon Duckett",
      category: categories[2]._id,
      description: "Every day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e-commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.",
      image: "HTML-CSS-HTML&CSS-design.jpg",
      price: 17.99,
      quantity: 600,
    },
    {
      name: "Learn to Code HTML & CSS",
      author: "Shay Howe",
      category: categories[2]._id,
      description: "HTML and CSS can be a little daunting at first but fear not. This book, based on Shay Howe's popular workshop covers the basics and breaks down the barrier to entry, showing readers how they can start using HTML and CSS through practical techniques today. They'll find accompanying code examples online, while they explore topics such as the different structures of HTML and CSS, and common terms. After establishing a basic understanding of HTML and CSS a deeper dive is taken into the box model and how to work with floats. The book includes an exercise focused on cleaning up a web page by improving the user interface and design, solely using HTML and CSS. With a few quick changes the web page changes shape and comes to life. Interactive, technically up-to-the-minute and easy-to-understand, this book will advance a student's skills to a professional level.",
      image: "HTML-CSS-learn-to-code-html-css.jpg",
      price: 30.62,
      quantity: 600,
    },
    {
      name: "Responsive Web Design with HTML 5 & CSS",
      author: "Jessica Minnick",
      category: categories[2]._id,
      description: "Readers discover the latest, industry-leading website development practices with this new book in the popular Shelly Cashman Series. For more than three decades, the Shelly Cashman Series has effectively introduced computer skills to millions of learners. Minnick's RESPONSIVE WEB DESIGN WITH HTML 5 & CSS, 9th edition, combines best practices with the most up-to-date tools available. The new edition equips readers with a solid foundation in HTML, CSS and responsive web design while illuminating deeper conceptual issues essential to today’s field of web development. In addition, a range of projects logically build in complexity and ensure thorough understanding.",
      image: "HTML-CSS-responsive-web-design.jpg",
      price: 90.79,
      quantity: 600,
    },
    {
      name: "CSS In Depth",
      author: "Keith J. Grant",
      category: categories[3]._id,
      description: "CSS in Depth exposes you to a world of CSS techniques that range from clever to mind-blowing. This instantly useful book is packed with creative examples and powerful best practices that will sharpen your technical skills and inspire your sense of design.",
      image: "ADVANCED-CSS-css-in-depth.jpg",
      price: 44.99,
      quantity: 600,
    },
    {
      name: "CSS Master Third Edition",
      author: "Tiffany B. Brown",
      category: categories[3]._id,
      description: "CSS has grown from a language for formatting documents into a robust language for designing web applications. Its simplicity is deceptive, however. It belies the complexity of the box model, stacking contexts, specificity, and the cascade. CSS mastery lies in understanding these concepts and how to take advantage of them.This book will show you how to write better, more efficient CSS, and to use the plethora of the new cutting-edge CSS features available to the front-end developer. You'll also learn to master tools that will improve your workflow.",
      image: "ADVANCED-CSS-css-master.jpg",
      price: 30.95,
      quantity: 600,
    },
    {
      name: "CSS The Definitive Edition",
      author: "Eric A. Meyer and Estelle Weyl",
      category: categories[3]._id,
      description: "CSS: The Definitive Guide, 3rd Edition, provides you with a comprehensive guide to CSS implementation, along with a thorough review of all aspects of CSS 2.1. Updated to cover Internet Explorer 7, Microsoft's vastly improved browser, this new edition includes content on positioning, lists and generated content, table layout, user interface, paged media, and more.",
      image: "ADVANCED-CSS-css-the-definitive-guide.jpg",
      price: 69.99,
      quantity: 600,
    },
    {
      name: "Modern CSS",
      author: "Joe Attardi",
      category: categories[3]._id,
      description: "Come on a tour of “modern” CSS in 2020. This example-driven book demonstrates the concepts by showing code examples, screenshots, and diagrams to help clearly communicate the information.",
      image: "ADVANCED-CSS-modern-css.jpg",
      price: 19.29,
      quantity: 600,
    },
    {
      name: "Pro CSS Techniques",
      author: "Jeff Croft, Ian Lloyd, and Dan Rubin",
      category: categories[3]._id,
      description: "This advanced CSS book is a must for any modern web developer to own. It is completely up-to-date, with information on browser support in all the latest versions and CSS levels 1, 2, and 3. Unlike beginner-level books that teach CSS in a lighthearted style, this one gets serious, giving CSS the proper, professional treatment it deserves. Each technique is presented in an informative tutorial style, with every point backed up by multiple real-world examples and case studies. The authors cover hacks and filters, code management, advanced layouts and styling, typography, and much more.",
      image: "ADVANCED-CSS-pro-css-techniques.jpg",
      price: 39.99,
      quantity: 600,
    },
    {
      name: "Coding with JavaScript for Dummies",
      author: "Chris Minnick and Eva Holland",
      category: categories[4]._id,
      description: "Coding with JavaScript For Dummies provides easy, hands-on instruction for anyone looking to learn this popular client-side language. No experience? No problem! This friendly guide starts from the very beginning and walks you through the basics, then shows you how to apply what you've learned to real projects. You'll start building right away, including web page elements and simple applications, so you can immediately see how JavaScript is used in the real world. Online exercises allow you to test your code and expand your skills, and the easy-to-follow instruction provides step-by-step guidance toward understanding the JavaScript syntax, applications, and language.",
      image: "JAVASCRIPT-coding-javascript-for-dummies.jpg",
      price: 34.99,
      quantity: 600,
    },
    {
      name: "Eloquent JavaScript Third Edition",
      author: "Marjin Haverbeke",
      category: categories[4]._id,
      description: "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
      image: "JAVASCRIPT-eloquent-javascript.jpg",
      price: 20.52,
      quantity: 600,
    },
    {
      name: "JavaScript from Beginner to Professional",
      author: "Laurence Lars Svekis, Maaike van Putten, and Rob Percival",
      category: categories[4]._id,
      description: "JavaScript from Beginner to Professional focuses on key programming concepts and Document Object Model manipulations that are used to solve common problems in professional web applications. These include data validation, manipulating the appearance of web pages, working with asynchronous and concurrent code.",
      image: "JAVASCRIPT-JavaScript-from-beginner-to-professional.jpg",
      price: 32.29,
      quantity: 600,
    },
    {
      name: "JavaScript The Comprehensive Guide",
      author: "Phillip Ackermann",
      category: categories[4]._id,
      description: "Begin your JavaScript journey with this comprehensive, hands-on guide. You’ll learn everything there is to know about professional JavaScript programming, from core language concepts to essential client-side tasks. Build dynamic web applications with step-by-step instructions and expand your knowledge by exploring server-side development and mobile development. Work with advanced language features, write clean and efficient code, and much more!",
      image: "JAVASCRIPT-JavaScript-the-comprehensive-guide.jpg",
      price: 48.81,
      quantity: 600,
    },
    {
      name: "JavaScript The Definitive Guide",
      author: "David Flanagan",
      category: categories[4]._id,
      description: "Since 1996, JavaScript: The Definitive Guide has been the bible for JavaScript programmers—a programmer's guide and comprehensive reference to the core language and to the client side JavaScript APIs defined by web browsers.The 6th edition covers HTML5 and ECMAScript 5. Many chapters have been completely rewritten to bring them in line with today's best web development practices. New chapters in this edition document jQuery and server side JavaScript. It's recommended for experienced programmers who want to learn the programming language of the Web, and for current JavaScript programmers who want to master it.",
      image: "JAVASCRIPT-JavaScript-the-definitive-guide.jpg",
      price: 38.49,
      quantity: 600,
    },
    {
      name: "API Fundamentals: An Easy Hands on Workbook for Beginners",
      author: "Pallavi Agarwal",
      category: categories[5]._id,
      description: "APIs are in the hands of every user who has a smart phone to say the least. If you want to understand what APIs really mean, how do they work and to put your knowledge of APIs to work quickly, this hands-on workbook will help you get started.",
      image: "APIS-api-fundamentals.jpg",
      price: 15.99,
      quantity: 600,
    },
    {
      name: "APIs A Strategy Guide",
      author: "Daniel Jacobson, Greg Brail, and Dan Woods",
      category: categories[5]._id,
      description: "Programmers used to be the only people excited about APIs, but now a growing number of companies see them as a hot new product channel. This concise guide describes the tremendous business potential of APIs, and demonstrates how you can use them to provide valuable services to clients, partners, or the public via the Internet. You will learn all the steps necessary for building a cohesive API business strategy from experts in the trenches. Facebook and Twitter APIs continue to be extremely successful, and many other companies find that API demand greatly exceeds website traffic. This book offers executives, business development teams, and other key players a complete roadmap for creating a viable API product.",
      image: "APIS-apis-a-strategy-guide.jpg",
      price: 24.99,
      quantity: 600,
    },
    {
      name: "Build APIs You Won't Hate",
      author: "Phil Sturgeon",
      category: categories[5]._id,
      description: "API development is becoming increasingly common for server-side developers thanks to the rise of front-end JavaScript frameworks, iPhone applications, and API-centric architectures. It might seem like grabbing stuff from a data source and shoving it out as JSON would be easy, but surviving changes in business logic, database schema updates, new features, or deprecated endpoints can be a nightmare. After finding many of the existing resources for API development to be lacking, Phil learned a lot of things the hard way through years of trial and error. This book aims to condense that experience, taking examples and explanations further than the trivial apples and pears nonsense tutorials often provide. By passing on some best practices and general good advice you can hit the ground running with API development, combined with some horror stories and how they were overcome/avoided/averted. This book will discuss the theory of designing and building APIs in any language or framework, with this theory applied in PHP-based examples.",
      image: "APIS-build-apis-you-wont-hate.jpg",
      price: 28.99,
      quantity: 600,
    },
    {
      name: "Mastering API Architecture",
      author: "James Gough, Daniel Bryant, and Matthew Auburn",
      category: categories[5]._id,
      description: "Most organizations with a web presence build and operate APIs; the doorway for customers to interact with the company's services. Designing, building, and managing these critical programs affect everyone in the organization, from engineers and product owners to C-suite executives. But the real challenge for developers and solution architects is creating an API platform from the ground up.",
      image: "APIS-mastering-api-architecture.jpg",
      price: 45.99,
      quantity: 600,
    },
    {
      name: "Beginning Node,js, Express & MongoDB Development",
      author: "Greg Lim",
      category: categories[6]._id,
      description: "In this book, we take you on a fun, hands-on and pragmatic journey to learning Node.js, Express and MongoDB development. You'll start building your first Node.js app within minutes. Every chapter is written in a bite-sized manner and straight to the point as I don't want to waste your time (and most certainly mine) on the content you don't need. In the end, you will have the skills to create a blog app and deploy it to the Internet.",
      image: "NODE-EXPRESS-beginning-nodejs-express-mongodb.jpg",
      price: 17.99,
      quantity: 600,
    },
    {
      name: "Express in Action",
      author: "Evan M. Hahn",
      category: categories[6]._id,
      description: "Express in Action is a carefully designed tutorial that teaches you how to build web applications using Node and Express.",
      image: "NODE-EXPRESS-express-in-action.jpg",
      price: 35.47,
      quantity: 600,
    },
    {
      name: "Get Programming with Node.js",
      author: "Jonathan Wexler",
      category: categories[6]._id,
      description: "Get Programming with Node. js teaches you to write server-side code in JavaScript using Node. js. In 37 fast-paced, fun, and practical lessons, you'll discover how to extend your existing JavaScript skills to write back-end code for your web applications.",
      image: "NODE-EXPRESS-get-programming-with-nodejs.jpg",
      price: 49.99,
      quantity: 600,
    },
    {
      name: "Node.js Easy Exercises",
      author: "Tony de Araujo",
      category: categories[6]._id,
      description: "Node.js Easy Exercises - Simple Page Navigation with Express teaches you the basics of build a multi-page application using JavaScript in a server-side environment with Node.js and Express.",
      image: "NODE-EXPRESS-node.js-easy-exercises.jpg",
      price: 10.99,
      quantity: 600,
    },
    {
      name: "Web Development with Node & Express",
      author: "Ethan Brown",
      category: categories[6]._id,
      description: "Build dynamic web applications with Express, a key component of the Node/JavaScript development stack. In this updated edition, author Ethan Brown teaches you Express fundamentals by walking you through the development of an example application. This hands-on guide covers everything from server-side rendering to API development suitable for usein single-page apps (SPAs).",
      image: "NODE-EXPRESS-web-dev-with-node-express-1st-edition.jpg",
      price: 31.49,
      quantity: 600,
    },
    {
      name: "Learn SQL DataBase Programming",
      author: "Josephine Bush",
      category: categories[7]._id,
      description: "Key FeaturesExplore all SQL statements in depth using a variety of examplesGet to grips with database querying, data aggregate, manipulation, and much moreUnderstand how to explore and process data of varying complexity to tell a storyBook Description",
      image: "SQL-NOSQL-learn-sql-db-programming.jpg",
      price: 39.99,
      quantity: 600,
    },
    {
      name: "NoSQL AND SQL Data Modeling",
      author: "Ted Hills",
      category: categories[7]._id,
      description: "How do we design for data when traditional design techniques cannot extend to new database technologies? In this era of big data and the Internet of Things, it is essential that we have the tools we need to understand the data coming to us faster than ever before, and to design databases and data processing systems that can adapt easily to ever-changing data schemas and ever-changing business requirements. There must be no intellectual disconnect between data and the software that manages it. It must be possible to extract meaning and knowledge from data to drive artificial intelligence applications. Novel NoSQL data organization techniques must be used side-by-side with traditional SQL databases. Are existing data modeling techniques ready for all of this?",
      image: "SQL-NOSQL-nosql-sql-data-modeling.jpg",
      price: 22.97,
      quantity: 600,
    },
    {
      name: "Practical SQL",
      author: "Anthony DeBarros",
      category: categories[7]._id,
      description: "Practical SQL is an approachable and fast-paced guide to SQL (Structured Query Language), the standard programming language for defining, organizing, and exploring data in relational databases. The book focuses on using SQL to find the story your data tells, with the popular open-source database PostgreSQL and the pgAdmin interface as its primary tools.",
      image: "SQL-NOSQL-practical-sql.jpg",
      price: 27.99,
      quantity: 600,
    },
    {
      name: "SQL For Smarties",
      author: "Joe Clelko",
      category: categories[7]._id,
      description: "Joe Celko, well-known columnist for the leading database magazines, shares his most useful time-saving tips and tricks for SQL programming to help readers progress from a casual SQL user to becoming an expert in SQL programming. Celko uses common programming problems as a basis for presenting a collection of advanced SQL programming techniques.",
      image: "SQL-NOSQL-sql-for-smarties.jpg",
      price: 53.53,
      quantity: 600,
    },
    {
      name: "SQL and NoSQL Databases",
      author: "Andreas Meier and Michael Kaufmann",
      category: categories[7]._id,
      description: "This book offers a comprehensive introduction to relational (SQL) and non-relational (NoSQL) databases. The authors thoroughly review the current state of database tools and techniques, and examine coming innovations.",
      image: "SQL-NOSQL-sql-nosql-databases.jpg",
      price: 54.99,
      quantity: 600,
    },
    {
      name: "Full Stack React: The Complete Guide to ReactJS and Friends",
      author:
        "Anthony Accomazzo, Clay Allsopp, Tyler McGinnis, Ari Lerner, David Guttman, and Nate Murray",
      category: categories[8]._id,
      description: "What if you could master the entire framework in less time, with solid foundations, without beating your head against the wall? Imagine how quickly you can get all of your work done with the right tools and best practices. Seriously, let's stop wasting time scouring Google, searching through incorrect, out-of-date, blog posts and get everything you need to be productive in one, well-organized place, complete with both simple and complex examples to get your app up and running. You'll learn what you need to know to work professionally and build solid, well-tested, optimized apps with ReactJS. This book is your definitive guide.",
      image: "REACT-fullstack-react.jpg",
      price: 59.99,
      quantity: 600,
    },
    {
      name: "Learning React",
      author: "Alex Banks and Eve Porcello",
      category: categories[8]._id,
      description: "If you want to learn how to build efficient user interfaces with React, this is your book. Authors Alex Banks and Eve Porcello show you how to create UIs with this small JavaScript library that can deftly display data changes on large-scale, data-driven websites without page reloads. Along the way, youll learn how to work with functional programming and the latest ECMAScript features.",
      image: "REACT-learning-react.jpg",
      price: 30.21,
      quantity: 600,
    },
    {
      name: "React Design Patterns and Best Practices",
      author: "Carlos Santana Roldan",
      category: categories[8]._id,
      description: "Build scalable, maintainable, and powerful React web apps with design patterns and insightful best practices",
      image: "REACT-react-design-patterns-best-practices.jpg",
      price: 41.99,
      quantity: 600,
    },
    {
      name: "React Explained",
      author: "Zac Gordon",
      category: categories[8]._id,
      description: "In React Explained, readers will dig deep into how React works and will learn how to build applications with it. While the focus is on building for the frontend on the web, many of the skills you will learn will also apply to writing React on the server side, for native applications and even for Virtual Reality environments.",
      image: "REACT-react-explained.jpg",
      price: 24.99,
      quantity: 600,
    },
    {
      name: "The Road to React",
      author: "Robin Wieruch",
      category: categories[8]._id,
      description: "In this book you will learn about all the fundamentals of React.js with Hooks while building a full-blown React application step by step. While you create the React application, every chapter will introduce you to a new React key feature. However, there is more than only the fundamentals: The book dives into related topics (e.g. React with TypeScript, Testing, Performance Optimizations) and advanced feature implementations like client- and server-side searching. At the end of the book, you will have a fully working deployed React application.",
      image: "REACT-the-road-to-react.jpg",
      price: 29.99,
      quantity: 600,
    },
    {
      name: "Full Stack Web Development For Beginners",
      author: "Riaz Ahmed",
      category: categories[9]._id,
      description: "This book is written for absolute beginners who want to become full-stack web application developers. To become a professional full-stack web developer you have to put on many hats. HTML5, CSS3, Bootstrap, JavaScript, MySQL, and PHP are the core technologies that you must be acquainted with to develop moderate data-driven web applications. All these technologies are voluminous and you need ample time to learn each one of them.",
      image: "FULL-STACK-fs-web-development-for-beginners.jpg",
      price: 9.99,
      quantity: 600,
    },
    {
      name: "Full Stack Web Development",
      author: "Sammie Smith",
      category: categories[9]._id,
      description: "This publication is focused on the modern Front-ends technology tools such as, HTML 5, CSS 3, Bootstrap 4, JavaScript, jQuery, GIT, GITHUB, and Version Control for Modern Web Development and Back-end technology tools such as, Node JS, Express, APIs, Embedded JavaScript (EJS), React JS, Database Fundamentals, SQL Databases, NoSQL Databases, MongoDB and Mongoose, Deployment + Authentication and Security for Modern Full-Stack Web Development.",
      image: "FULL-STACK-full-stack-web-development.jpg",
      price: 35.99,
      quantity: 600,
    },
    {
      name: "FullStack Rust: The Complete Guide to Building Apps with the Rust Programming Language and Friends",
      author: "Andrew Weiss",
      category: categories[9]._id,
      description: "Fullstack Rust: The Complete Guide to Building Apps with the Rust Programming Language and Friends. Learn to build performance-critical Rust apps. The Rust language is a way to write incredibly fast - and safe - code. Its being used to build tools at Google, Facebook, Amazon, and many other companies where performance is critical. While there are some good resources on how to learn the Rust programming language by itself, what these other books don't teach is how to build applications with Rust. Fullstack Rust solves that. In this book we show you how to use Rust to build incredibly fast web-servers, build command-line tools, and compile apps to run in the browser with Web Assembly (WASM).",
      image: "FULL-STACK-fullstack-rust.jpg",
      price: 79.99,
      quantity: 600,
    },
    {
      name: "Modern Full-Stack Development",
      author: "Frank Zammetti",
      category: categories[9]._id,
      description: "Explore what React, Node, Python, Django, TypeScript, Webpack, and Docker have to offer individually, and how they all fit together in modern app development. This updated version will show you how to build apps with React, Node.js or Django, and TypeScript, and how Webpack can be used to optimize and organize your code for deployment.",
      image: "FULL-STACK-modern-fs-development.jpg",
      price: 38.29,
      quantity: 600,
    },
    {
      name: "The Full Stack Developer",
      author: "Chris Northwood",
      category: categories[9]._id,
      description: "Understand the technical foundations, as well as the non-programming skills needed to be a successful full stack web developer. This book reveals the reasons why a truly successful full stack developer does more than write code. You will learn the principles of the topics needed to help a developer new to agile or full stack working—UX, project management, QA, product management, and more— all from the point of view of a developer. Covering these skills alongside the fundamentals and foundations of modern web development, rather than specifics of current technologies and frameworks (which can age quickly), all programming examples are given in the context of the web as it is in 2018.",
      image: "FULL-STACK-the-fs-developer.jpg",
      price: 41.49,
      quantity: 600,
    },
    {
      name: "Beginning Git and GitHub",
      author: "Mariot Tsitoara",
      category: categories[10]._id,
      description:
        "A Comprehensive Guide to Version Control, Project Management, and Teamwork for the New Developer",
      image: "Beginning-Git-and-Github.jpeg",
      price: 22.41,
      quantity: 500,
    },
    {
      name: "Git & GitHub the First Steps",
      author: "David Hockley",
      category: categories[10]._id,
      description:
        "Learn Git & Github with step-by-step practical examples, We see the step-by-step path that developers use to work with the essential tool that is git.",
      image: "Git-&-GitHub-the-First-Steps.jpg",
      price: 8.99,
      quantity: 100,
    },
    {
      name: "GitHub for Dummies",
      author: "Sarah Guthals and Phil Haack",
      category: categories[10]._id,
      description:
        "Create a repository for your coding projects, Personalize your work flow with GitHub tools and integrations, Collaborate on open source software projects",
      image: "GitHub-for-Dummies.jpg",
      price: 34.99,
      quantity: 500,
    },
    {
      name: "Git",
      author: "Jameson Garner",
      category: categories[10]._id,
      description:
        "Learn the basics of Git through detailed and easy to follow along screenshots. Start using Git today!This book is designed to cut academic theory to just the key concepts and focus on basics tasks in Git in order to be productive quickly. Students can expect to learn the minimum needed to start using Git in less than an hour.",
      image: "The-Ultimate-Guide-For-Beginners-to-Learn-Git.jpg",
      price: 17.34,
      quantity: 200,
    },
    {
      name: "Version Control With Git",
      author: "Jon Loeliger and Matthew McCullough",
      category: categories[10]._id,
      description:
        "Get up to speed on Git for tracking, branching, merging, and managing code revisions. Through a series of step-by-step tutorials, this practical guide takes you quickly from Git fundamentals to advanced techniques, and provides friendly yet rigorous advice for navigating the many functions of this open source version control system.",
      image: "Version-Control-With-Git.jpg",
      price: 44.99,
      quantity: 350,
    },
    {
      name: "Python Crash Course",
      author: "Eric Matthes",
      category: categories[11]._id,
      description:
        "Learn how to make your programs interactive and test your code safely before adding it to a project. You will put your new knowledge into practice by creating a Space Invaders–inspired arcade game, building a set of data visualizations with Pythons handy libraries, and deploying a simple application online.",
      image: "Python-Crash-Course.jpg",
      price: 30.49,
      quantity: 300,
    },
    {
      name: "Python For Data Analysis",
      author: "Wes McKinney",
      category: categories[11]._id,
      description:
        "Get complete instructions for manipulating, processing, cleaning, and crunching datasets in Python. Updated for Python 3.6, the second edition of this hands-on guide is packed with practical case studies that show you how to solve a broad set of data analysis problems effectively.",
      image: "Python-for-Data-Analysis.jpg",
      price: 60.81,
      quantity: 150,
    },
    {
      name: "Python for Dummies",
      author: "Stef Maruch and Aahz Maruch",
      category: categories[11]._id,
      description:
        "Python is one of the most powerful, easy-to-read programming languages around, but it does have its limitations. This general purpose, high-level language that can be extended and embedded is a smart option for many programming problems, but a poor solution to others.",
      image: "Python-for-Dummies.jpeg",
      price: 29.99,
      quantity: 700,
    },
    {
      name: "Python Programming for Beginners",
      author: "Amz Press",
      category: categories[11]._id,
      description:
        "Python is a programming language that has existed for over 20 years. The history of Python started in the late 1980s when its founder, Guido van Rossum, started working on it.",
      image: "Python-Programming-for-Beginners.jpg",
      price: 20.69,
      quantity: 300,
    },
    {
      name: "Think Python",
      author: "Allen B. Downey",
      category: categories[11]._id,
      description:
        "If you want to learn how to program, working with Python is an excellent way to start. This hands-on guide takes you through the language a step at a time, beginning with basic programming concepts before moving on to functions, recursion, data structures, and object-oriented design.",
      image: "Think-Python.jpg",
      price: 29.74,
      quantity: 200,
    },
  ]);
  console.log("products seeded");

  await User.deleteMany();

  await User.create({
    firstName: "Pamela",
    lastName: "Washington",
    email: "pamela@testmail.com",
    password: "password12345",
    orders: [
      {
        products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  });

  await User.create({
    firstName: "Elijah",
    lastName: "Holt",
    email: "eholt@testmail.com",
    password: "password12345",
  });

  console.log("users seeded");

  process.exit();
});
